CREATE TABLE IF NOT EXISTS openclaw_skill_review (
  id varchar(36) NOT NULL COMMENT 'Primary key',
  draft_id varchar(36) NOT NULL COMMENT 'Skill draft id',
  version_no int NOT NULL COMMENT 'Submitted draft version number',
  skill_id varchar(36) DEFAULT NULL COMMENT 'Formal skill id when available',
  workspace_id varchar(36) DEFAULT NULL COMMENT 'Workspace id when drafts are workspace-bound',
  submitter_id varchar(36) NOT NULL COMMENT 'Submitter sys_user.id',
  submitter_username varchar(100) DEFAULT NULL,
  reviewer_id varchar(36) DEFAULT NULL COMMENT 'Reviewer sys_user.id',
  reviewer_username varchar(100) DEFAULT NULL,
  status varchar(32) NOT NULL COMMENT 'SUBMITTED/APPROVED/REJECTED/CANCELLED',
  file_snapshot_json longtext NOT NULL COMMENT 'Immutable submitted file snapshot JSON',
  file_hash varchar(64) NOT NULL COMMENT 'Submitted snapshot SHA-256 hash',
  test_run_id varchar(36) NOT NULL COMMENT 'Bound successful test run id',
  test_report_json longtext DEFAULT NULL COMMENT 'Immutable test report JSON',
  ai_record_ids_json text DEFAULT NULL COMMENT 'Related AI edit/repair record id list JSON',
  submit_comment varchar(1000) DEFAULT NULL,
  review_comment varchar(1000) DEFAULT NULL,
  submitted_time datetime DEFAULT NULL,
  reviewed_time datetime DEFAULT NULL,
  published_version_no int DEFAULT NULL,
  published_skill_id varchar(36) DEFAULT NULL,
  create_by varchar(50) DEFAULT NULL,
  create_time datetime DEFAULT NULL,
  update_by varchar(50) DEFAULT NULL,
  update_time datetime DEFAULT NULL,
  del_flag tinyint DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_openclaw_skill_review_draft_version (draft_id, version_no),
  KEY idx_openclaw_skill_review_status (status),
  KEY idx_openclaw_skill_review_submitter (submitter_id),
  KEY idx_openclaw_skill_review_reviewer (reviewer_id),
  KEY idx_openclaw_skill_review_test (test_run_id),
  KEY idx_openclaw_skill_review_skill (skill_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OpenClaw Skill fixed-version review';

CREATE TABLE IF NOT EXISTS openclaw_published_skill_version (
  id varchar(36) NOT NULL COMMENT 'Primary key',
  skill_id varchar(36) NOT NULL COMMENT 'Formal skill id',
  review_id varchar(36) NOT NULL COMMENT 'Source review id',
  draft_id varchar(36) NOT NULL COMMENT 'Source draft id',
  draft_version_no int NOT NULL COMMENT 'Source draft version number',
  published_version_no int NOT NULL COMMENT 'Formal published version sequence',
  file_snapshot_json longtext NOT NULL COMMENT 'Immutable published file snapshot JSON',
  file_hash varchar(64) NOT NULL COMMENT 'Published snapshot SHA-256 hash',
  status varchar(32) NOT NULL COMMENT 'PUBLISHED/DEPRECATED',
  published_by varchar(100) DEFAULT NULL,
  published_time datetime DEFAULT NULL,
  create_by varchar(50) DEFAULT NULL,
  create_time datetime DEFAULT NULL,
  update_by varchar(50) DEFAULT NULL,
  update_time datetime DEFAULT NULL,
  del_flag tinyint DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_openclaw_published_skill_version (skill_id, published_version_no),
  UNIQUE KEY uk_openclaw_published_review (review_id),
  KEY idx_openclaw_published_skill (skill_id),
  KEY idx_openclaw_published_draft (draft_id, draft_version_no),
  KEY idx_openclaw_published_status (status),
  KEY idx_openclaw_published_hash (file_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OpenClaw immutable published Skill versions';
