CREATE TABLE IF NOT EXISTS openclaw_skill_ai_edit_record (
  id varchar(36) NOT NULL COMMENT 'Primary key',
  draft_id varchar(36) NOT NULL COMMENT 'Skill draft id',
  skill_id varchar(36) DEFAULT NULL COMMENT 'Base published skill id',
  workspace_id varchar(36) DEFAULT NULL COMMENT 'Reserved workspace id',
  user_id varchar(36) NOT NULL COMMENT 'sys_user.id',
  user_instruction text DEFAULT NULL COMMENT 'Natural-language edit instruction',
  summary text DEFAULT NULL,
  files_json longtext NOT NULL COMMENT 'Structured AI file suggestions',
  warnings_json longtext DEFAULT NULL,
  base_version varchar(128) NOT NULL COMMENT 'Draft version at preview time',
  base_hash varchar(128) NOT NULL COMMENT 'Draft file tree hash at preview time',
  status varchar(32) NOT NULL DEFAULT 'PREVIEW' COMMENT 'PREVIEW/APPLIED/FAILED',
  error_message text DEFAULT NULL,
  applied_time datetime DEFAULT NULL,
  create_by varchar(50) DEFAULT NULL,
  create_time datetime DEFAULT NULL,
  update_by varchar(50) DEFAULT NULL,
  update_time datetime DEFAULT NULL,
  del_flag tinyint DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_openclaw_skill_ai_edit_draft (draft_id),
  KEY idx_openclaw_skill_ai_edit_user (user_id),
  KEY idx_openclaw_skill_ai_edit_status (status),
  KEY idx_openclaw_skill_ai_edit_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OpenClaw skill AI edit preview record';
